name: 'monzo_project'
version: '1.0'
profile: 'bigquery'

vars:
  dev_limit: true

  
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  +persist_docs:
    columns: true

    base:
      +docs:
        node_color: green
      materialized: view
      
    intermediate:
      +docs:
        node_color: yellow
      materialized: table

    marts: 
      +docs:
        node_color: blue
      materialized: table

  elementary:
    +meta:
      owner: monzo
    enabled: "{{ target.name in ['production'] }}"
    schema: elementary

tests:
  +meta:
    owner: "monzo"
  +store_failures: true
  
     